BBMRI-ERIC/negotiator

dbdiagram

This PR adds the DB diagram source and removes request_query_link and project_request_link tables

DB changes

---

Dockerfile
docker-compose.yml
pom.xml

Non root docker image
Non branch specific docker build
Simplified docker-compose

New docker deployment

---

src/main/java/eu/bbmri/eric/csit/service/negotiator/api/controller/v3/AccessCriteriaSetController.java
src/main/java/eu/bbmri/eric/csit/service/negotiator/api/dto/access_criteria/AccessCriteriaSetDTO.java
src/main/java/eu/bbmri/eric/csit/service/negotiator/database/model/AccessCriteriaSet.java
src/main/java/eu/bbmri/eric/csit/service/negotiator/database/model/AccessCriteriaSetLink.java
src/main/resources/data-h2.sql
src/test/java/eu/bbmri/eric/csit/service/negotiator/api/v3/AccessCriteriaSetControllerTests.java

Now the access criteria are returned ordered as specified in the db

feat: implement ordering of access criteria

---

src/main/java/eu/bbmri/eric/csit/service/negotiator/configuration/SecurityConfig.java
src/main/resources/application.yaml
src/main/resources/data-test.sql

Adds support to at+jwt token type used by the aai

access token jwt support

---

src/main/java/eu/bbmri/eric/csit/service/negotiator/configuration/SecurityConfig.java

fix: fixes jwt decoder

---

src/main/java/eu/bbmri/eric/csit/service/negotiator/configuration/SecurityConfig.java

Adds support to each kind of authentication for v2 endpoint

authorization for v2 backward compatibility

---

LICENSE

Add GNU Affero General Public License

---

src/main/java/eu/bbmri/eric/csit/service/negotiator/api/controller/v3/NegotiationController.java

Fix fetching of negotiations for representative

---

src/main/java/eu/bbmri/eric/csit/service/negotiator/api/controller/v3/NegotiationController.java
src/main/java/eu/bbmri/eric/csit/service/negotiator/configuration/OAuthSecurityConfig.java
src/test/java/eu/bbmri/eric/csit/service/negotiator/integration/api/v3/NegotiationControllerTests.java

Add REST endpoint for fetching lifecycle stages

---

src/main/resources/data.sql

Add BBMRI template from v2

---

src/main/java/eu/bbmri/eric/csit/service/negotiator/configuration/MailConfig.java
src/main/java/eu/bbmri/eric/csit/service/negotiator/service/NegotiationServiceImpl.java
src/main/java/eu/bbmri/eric/csit/service/negotiator/service/NotificationServiceImpl.java

Fix email configuration

---

src/main/java/eu/bbmri/eric/csit/service/negotiator/database/model/Organization.java
src/main/java/eu/bbmri/eric/csit/service/negotiator/database/model/Resource.java
src/main/java/eu/bbmri/eric/csit/service/negotiator/database/repository/OrganizationRepository.java
src/main/java/eu/bbmri/eric/csit/service/negotiator/dto/OrganizationDTO.java
src/main/java/eu/bbmri/eric/csit/service/negotiator/dto/request/ResourceDTO.java
src/main/resources/application-test.yaml
src/test/java/eu/bbmri/eric/csit/service/negotiator/integration/repository/OrganizationRepositoryTest.java
src/test/java/eu/bbmri/eric/csit/service/negotiator/unit/mappers/ResourceModelMapperTest.java
src/test/java/eu/bbmri/eric/csit/service/negotiator/unit/model/OrganizationTest.java

Adds a basic data model for represneting Organizations.

feat: basic data model for an Organization

---

src/main/java/eu/bbmri/eric/csit/service/negotiator/configuration/auth/JwtAuthenticationConverter.java
src/main/java/eu/bbmri/eric/csit/service/negotiator/database/model/Negotiation.java
src/main/java/eu/bbmri/eric/csit/service/negotiator/service/NegotiationServiceImpl.java

fix: database transactions

---

.github/scripts/check_health.sh
.github/scripts/wait_for_url.sh
.github/workflows/CI.yml

ci: add smoke test

---

src/main/java/eu/bbmri/eric/csit/service/negotiator/dto/post/PostCreateDTO.java
src/main/java/eu/bbmri/eric/csit/service/negotiator/mappers/PostModelMapper.java
src/main/java/eu/bbmri/eric/csit/service/negotiator/service/PostServiceImpl.java
src/test/java/eu/bbmri/eric/csit/service/negotiator/integration/api/v3/TestUtils.java

fix: fixes private posts

---

src/main/java/eu/bbmri/eric/csit/service/negotiator/configuration/state_machine/negotiation/PersistStateChangeListener.java
src/main/java/eu/bbmri/eric/csit/service/negotiator/database/model/Person.java
src/main/java/eu/bbmri/eric/csit/service/negotiator/database/repository/PersonRepository.java
src/main/java/eu/bbmri/eric/csit/service/negotiator/service/PersonServiceImpl.java
src/main/java/eu/bbmri/eric/csit/service/negotiator/service/RepresentativeNegotiationServiceImpl.java
src/main/resources/application-prod.yaml

fix: lazy loading

---

src/main/resources/application-dev.yaml

fix: oauth audiences

---

src/main/java/eu/bbmri/eric/csit/service/negotiator/configuration/security/auth/CustomJWTAuthConverter.java

Fixes parsing of entitlements from a JWT.

fix: entitlements parsing

---

src/main/java/eu/bbmri/eric/csit/service/negotiator/configuration/security/auth/CustomJWTAuthConverter.java

fix: client credentials token flag

---

src/main/java/eu/bbmri/eric/csit/service/negotiator/configuration/security/auth/CustomJWTAuthConverter.java

fix: scopes parsing

---

.github/workflows/CI.yml
README.md
pom.xml
src/test/java/eu/bbmri_eric/negotiator/unit/converters/ConverterTest.java

tests: increase coverage

---

pom.xml

fix: update postgresql to 42.6.0

---

.github/workflows/CI.yml
Dockerfile
README.md
pom.xml
src/main/java/eu/bbmri_eric/negotiator/configuration/DevDatabaseConfiguration.java
src/main/resources/application.yaml
src/test/java/TestNegotiatorApplication.java

Fixes the dev mode configuration and documentation.

Fix dev mode configuration

---

src/main/java/eu/bbmri_eric/negotiator/database/model/AccessForm.java
src/main/java/eu/bbmri_eric/negotiator/service/AccessFormServiceImpl.java
src/test/java/eu/bbmri_eric/negotiator/integration/service/AccessFormServiceTest.java

Fix the mechanism for combining access forms.

Fix the mechanism for combining access forms

---

.github/workflows/CI.yml
src/main/resources/db/dev/migration/R__Initial_data.sql
src/main/resources/db/migration/postgresql/V3__add_dynamic_access_forms.sql

fix: access forms db migration

---

src/main/java/eu/bbmri_eric/negotiator/configuration/state_machine/negotiation/DisablePostsAction.java
src/main/java/eu/bbmri_eric/negotiator/configuration/state_machine/negotiation/NegotiationStateMachineConfig.java
src/main/java/eu/bbmri_eric/negotiator/service/NegotiationService.java
src/main/java/eu/bbmri_eric/negotiator/service/NegotiationServiceImpl.java
src/test/java/eu/bbmri_eric/negotiator/integration/service/NegotiationLifecycleServiceImplTest.java
src/test/java/eu/bbmri_eric/negotiator/unit/model/NegotiationLifecycleRecordTest.java
src/test/java/eu/bbmri_eric/negotiator/unit/service/NegotiationServiceTest.java

Adds functionality to disable posts in abandoned negotiations

feat: Add functionality to disable posts in abandoned negotiations

---

src/main/java/eu/bbmri_eric/negotiator/configuration/WebConfig.java
src/main/resources/application.yaml
src/test/java/eu/bbmri_eric/negotiator/integration/api/SecurityTest.java

Adds configuration properties for CORS headers.

Feat: add cors configurations

---

src/main/java/eu/bbmri_eric/negotiator/database/repository/NegotiationRepository.java
src/main/java/eu/bbmri_eric/negotiator/service/NegotiationLifecycleServiceImpl.java
src/main/java/eu/bbmri_eric/negotiator/service/ResourceLifecycleServiceImpl.java
src/test/java/eu/bbmri_eric/negotiator/integration/service/NegotiationLifecycleServiceImplTest.java

Fix memory issues caused by lifecycle endpoints on large requests.

Fix memory issues caused by lifecycle endpoints on large requests 

---

src/main/java/eu/bbmri_eric/negotiator/service/PersonServiceImpl.java

feat: add logging of auth changes

---

pom.xml
src/main/java/eu/bbmri_eric/negotiator/api/controller/v2/QueryV2Controller.java
src/main/java/eu/bbmri_eric/negotiator/api/controller/v3/AccessFormController.java
src/main/java/eu/bbmri_eric/negotiator/api/controller/v3/AttachmentController.java
src/main/java/eu/bbmri_eric/negotiator/api/controller/v3/DiscoverServiceController.java
src/main/java/eu/bbmri_eric/negotiator/api/controller/v3/NegotiationController.java
src/main/java/eu/bbmri_eric/negotiator/api/controller/v3/NotificationController.java
src/main/java/eu/bbmri_eric/negotiator/api/controller/v3/OrganizationController.java
src/main/java/eu/bbmri_eric/negotiator/api/controller/v3/PostController.java
src/main/java/eu/bbmri_eric/negotiator/api/controller/v3/RequestController.java
src/main/java/eu/bbmri_eric/negotiator/api/controller/v3/ResourceController.java
src/main/java/eu/bbmri_eric/negotiator/api/controller/v3/UserController.java
src/main/java/eu/bbmri_eric/negotiator/api/controller/v3/utils/NegotiationRole.java
src/main/java/eu/bbmri_eric/negotiator/api/controller/v3/utils/NegotiationSortField.java
src/main/java/eu/bbmri_eric/negotiator/configuration/BaseConfig.java
src/main/java/eu/bbmri_eric/negotiator/configuration/SwaggerConfig.java
src/main/java/eu/bbmri_eric/negotiator/converters/NegotiationRoleConverter.java
src/main/java/eu/bbmri_eric/negotiator/database/repository/NegotiationSpecification.java
src/main/java/eu/bbmri_eric/negotiator/dto/negotiation/NegotiationFilters.java
src/main/java/eu/bbmri_eric/negotiator/mappers/NegotiationModelAssembler.java
src/main/java/eu/bbmri_eric/negotiator/mappers/UserModelAssembler.java
src/main/resources/application-dev.yaml
src/main/resources/application.yaml

The PR does not modify any bussiness code, it just adds annotations and confiugrations for swagger documentation,

Improved Swagger and OpenAPI documentation

---

pom.xml
src/main/java/eu/bbmri_eric/negotiator/configuration/ExceptionHandlerFilter.java
src/main/java/eu/bbmri_eric/negotiator/configuration/security/OAuthSecurityConfig.java
src/main/java/eu/bbmri_eric/negotiator/configuration/security/auth/CustomJWTAuthConverter.java
src/main/resources/application.yaml
src/test/java/eu/bbmri_eric/negotiator/integration/api/SecurityTest.java

Add API endpoints for prometheus monitoring.

Add API endpoints for prometheus monitoring

---

src/main/java/eu/bbmri_eric/negotiator/service/RequestServiceImpl.java

Add resource ID to WrongRequest errors.

fix(requests): Include resource id in error message

---

.github/workflows/CI.yml
src/main/java/eu/bbmri_eric/negotiator/service/ResourceLifecycleServiceImpl.java
src/test/java/eu/bbmri_eric/negotiator/integration/service/NegotiationLifecycleServiceImplTest.java
src/test/java/eu/bbmri_eric/negotiator/integration/service/UserNotificationServiceTest.java

Fixes an issue when anyone could update the status of resources.

fix(lifecycle): change security rule checks on resource lifecycle

---

.github/workflows/CI.yml
src/main/java/eu/bbmri_eric/negotiator/service/PostServiceImpl.java
src/main/java/eu/bbmri_eric/negotiator/service/ResourceLifecycleServiceImpl.java
src/main/java/eu/bbmri_eric/negotiator/service/UserNotificationServiceImpl.java
src/test/java/eu/bbmri_eric/negotiator/integration/service/NegotiationLifecycleServiceImplTest.java
src/test/java/eu/bbmri_eric/negotiator/integration/service/UserNotificationServiceTest.java
src/test/java/eu/bbmri_eric/negotiator/unit/service/PostServiceTest.java

fix: allow administrators to post comments during approval phase

---

src/main/java/eu/bbmri_eric/negotiator/configuration/MailConfig.java
src/main/resources/application.yaml

This PR adds more configuration options for SMTP configuration.

feat(MailConfig): add more configuration options for SMTP connection

---

src/main/java/eu/bbmri_eric/negotiator/common/exceptions/NegotiatorExceptionHandler.java
src/main/java/eu/bbmri_eric/negotiator/governance/network/NetworkController.java
src/main/java/eu/bbmri_eric/negotiator/governance/network/NetworkStatistics.java
src/main/java/eu/bbmri_eric/negotiator/governance/network/NetworkStatisticsService.java
src/main/java/eu/bbmri_eric/negotiator/governance/network/NetworkStatisticsServiceImpl.java
src/main/java/eu/bbmri_eric/negotiator/governance/network/SimpleNetworkStatistics.java
src/main/java/eu/bbmri_eric/negotiator/negotiation/NegotiationRepository.java
src/main/java/eu/bbmri_eric/negotiator/negotiation/NegotiationServiceImpl.java
src/main/java/eu/bbmri_eric/negotiator/user/Person.java
src/main/java/eu/bbmri_eric/negotiator/user/PersonModelMapper.java
src/main/java/eu/bbmri_eric/negotiator/user/UserController.java
src/main/java/eu/bbmri_eric/negotiator/user/UserInfoModel.java
src/main/java/eu/bbmri_eric/negotiator/user/UserModelAssembler.java
src/main/java/eu/bbmri_eric/negotiator/user/UserResponseModel.java
src/main/resources/db/test/migration/R__Initial_data.sql
src/test/java/eu/bbmri_eric/negotiator/integration/api/v3/NetworkControllerTests.java
src/test/java/eu/bbmri_eric/negotiator/integration/api/v3/UserControllerTest.java
src/test/java/eu/bbmri_eric/negotiator/unit/controller/UserControllerTest.java

This PR adds functionality for retrieving basic network statistics.

feat(network): add support for basic statistics

---

src/main/java/eu/bbmri_eric/negotiator/common/configuration/security/oauth2/CustomJWTAuthConverter.java

Updates user info based on perun access token.

fix: updates person if user info of perun token changed

---

.github/compose-overrides/compose.override.system.yaml
.github/oauth-test/compose.yaml
README.md
src/main/resources/application-dev.yaml
src/main/resources/application-prod.yaml
src/main/resources/application.yaml

Removes redundant properties from the property files and the compose.yml

refactor: remove redundant properties from config files

---

.github/workflows/CI.yml
docs/.vitepress/config.ts
docs/Makefile
docs/README.md
docs/deployment.md
docs/index.md
docs/package-lock.json
docs/package.json

Adds GitHub pages documentation

docs: add github pages

---

src/main/java/eu/bbmri_eric/negotiator/governance/resource/ResourceServiceImpl.java
src/main/java/eu/bbmri_eric/negotiator/governance/resource/dto/ResourceStateMetadataDto.java
src/main/java/eu/bbmri_eric/negotiator/negotiation/Negotiation.java
src/main/java/eu/bbmri_eric/negotiator/negotiation/NegotiationController.java
src/main/java/eu/bbmri_eric/negotiator/negotiation/NegotiationResourceLink.java
src/main/java/eu/bbmri_eric/negotiator/negotiation/dto/UpdateResourcesDTO.java
src/main/java/eu/bbmri_eric/negotiator/negotiation/mappers/NegotiationModelAssembler.java
src/main/java/eu/bbmri_eric/negotiator/negotiation/state_machine/negotiation/NegotiationLifecycleServiceImpl.java
src/main/java/eu/bbmri_eric/negotiator/negotiation/state_machine/resource/NegotiationResourceState.java
src/main/java/eu/bbmri_eric/negotiator/negotiation/state_machine/resource/ResourceLifecycleServiceImpl.java
src/main/java/eu/bbmri_eric/negotiator/user/Person.java
src/test/java/eu/bbmri_eric/negotiator/integration/api/v3/NegotiationControllerTests.java
src/test/java/eu/bbmri_eric/negotiator/integration/repository/NotificationRepositoryTest.java
src/test/java/eu/bbmri_eric/negotiator/integration/service/NegotiationLifecycleServiceImplTest.java
src/test/java/eu/bbmri_eric/negotiator/unit/mappers/NegotiationModelAssemblerTest.java

This PR makes the necessary modifications to the API so that the representative can override the status of a Resource they represent in a Negotiation.

feat(negotiation): enable the Representative to override the status for Resource

---

docs/.vitepress/config.mts

ci: fix docs building job

---

docs/deployment.md

docs: add table explaining custom appplication properties and LS-Login integration

---

src/main/java/eu/bbmri_eric/negotiator/common/AuthenticatedUserContext.java
src/main/java/eu/bbmri_eric/negotiator/governance/network/NetworkController.java
src/main/java/eu/bbmri_eric/negotiator/governance/resource/NonRepresentedResourcesHandlerImpl.java
src/main/java/eu/bbmri_eric/negotiator/governance/resource/ResourceServiceImpl.java
src/main/java/eu/bbmri_eric/negotiator/negotiation/NegotiationAccessManager.java
src/main/java/eu/bbmri_eric/negotiator/negotiation/NegotiationAccessManagerImpl.java
src/main/java/eu/bbmri_eric/negotiator/negotiation/NegotiationController.java
src/main/java/eu/bbmri_eric/negotiator/negotiation/NegotiationServiceImpl.java
src/main/java/eu/bbmri_eric/negotiator/negotiation/state_machine/negotiation/NegotiationLifecycleServiceImpl.java
src/main/java/eu/bbmri_eric/negotiator/negotiation/state_machine/resource/ResourceLifecycleServiceImpl.java
src/main/java/eu/bbmri_eric/negotiator/post/PostService.java
src/main/java/eu/bbmri_eric/negotiator/post/PostServiceImpl.java
src/main/java/eu/bbmri_eric/negotiator/user/Person.java
src/main/java/eu/bbmri_eric/negotiator/user/PersonRepository.java
src/main/resources/db/test/migration/R__Initial_data.sql
src/test/java/eu/bbmri_eric/negotiator/integration/api/v3/NegotiationControllerTests.java
src/test/java/eu/bbmri_eric/negotiator/integration/api/v3/NetworkControllerTests.java
src/test/java/eu/bbmri_eric/negotiator/integration/api/v3/PostControllerTests.java
src/test/java/eu/bbmri_eric/negotiator/integration/api/v3/ResourceControllerTests.java
src/test/java/eu/bbmri_eric/negotiator/integration/notification/RepresentativeNotificationsTest.java
src/test/java/eu/bbmri_eric/negotiator/integration/service/NegotiationLifecycleServiceImplTest.java
src/test/java/eu/bbmri_eric/negotiator/unit/service/PostServiceTest.java

Modifies the system so that the Network Manager is able to read relevant negotiations as well as post comments. Since this required changes to multiple components some of them, such as Post Service had to be refactored.

feat: give network manager access to negotiations

---

src/main/java/eu/bbmri_eric/negotiator/governance/network/Network.java
src/main/java/eu/bbmri_eric/negotiator/governance/network/NetworkCreateDTO.java
src/main/java/eu/bbmri_eric/negotiator/governance/network/NetworkCreateModelMapper.java
src/main/java/eu/bbmri_eric/negotiator/governance/network/NetworkDTO.java
src/main/java/eu/bbmri_eric/negotiator/governance/network/NetworkServiceImpl.java
src/main/java/eu/bbmri_eric/negotiator/governance/organization/Organization.java
src/main/java/eu/bbmri_eric/negotiator/governance/organization/OrganizationCreateDTO.java
src/main/java/eu/bbmri_eric/negotiator/governance/organization/OrganizationCreateModelMapper.java
src/main/java/eu/bbmri_eric/negotiator/governance/organization/OrganizationDTO.java
src/main/java/eu/bbmri_eric/negotiator/governance/organization/OrganizationServiceImpl.java
src/main/java/eu/bbmri_eric/negotiator/governance/resource/Resource.java
src/main/java/eu/bbmri_eric/negotiator/governance/resource/ResourceCreateModelMapper.java
src/main/java/eu/bbmri_eric/negotiator/governance/resource/ResourceServiceImpl.java
src/main/java/eu/bbmri_eric/negotiator/governance/resource/dto/ResourceCreateDTO.java
src/main/java/eu/bbmri_eric/negotiator/governance/resource/dto/ResourceResponseModel.java
src/main/java/eu/bbmri_eric/negotiator/governance/resource/dto/ResourceUpdateDTO.java
src/main/resources/db/migration/V20__add_org_res_ntw_new_columns.sql
src/main/resources/db/test/migration/R__Initial_data.sql
src/test/java/eu/bbmri_eric/negotiator/integration/api/v3/NetworkControllerTests.java
src/test/java/eu/bbmri_eric/negotiator/integration/api/v3/OrganizationControllerTest.java
src/test/java/eu/bbmri_eric/negotiator/integration/api/v3/ResourceControllerTests.java
src/test/java/eu/bbmri_eric/negotiator/unit/controller/ResourceControllerTest.java
src/test/java/eu/bbmri_eric/negotiator/unit/mappers/NetworkCreateModelMapperTest.java
src/test/java/eu/bbmri_eric/negotiator/unit/mappers/OrganizationCreateModelMapperTest.java
src/test/java/eu/bbmri_eric/negotiator/unit/mappers/ResourceCreateModelMapperTest.java
src/test/java/eu/bbmri_eric/negotiator/unit/mappers/ResourceModelMapperTest.java
src/test/java/eu/bbmri_eric/negotiator/unit/model/ResourceTest.java

This pull request updates the Organization, Resource and Network entities by adding: 
- Description, contactEmail and uri attributes to Organization; 
- contactEmail and uri attributes to Resource;
- description attribute to Network 

feat:add attributes to Organization, Resource and Network

---

frontend/package.json
frontend/src/assets/scss/theme.scss
frontend/vue.config.js
frontend/yarn.lock

feat: update vite dependencies

---

.github/workflows/CI.yml
compose.yml
frontend/.dockerignore
frontend/src/components/NewRequestButton.vue
frontend/src/config/featureFlags.js
frontend/start.sh

Fixes bug for parsing env variables in the UI docker image.

fix: start.sh regex

---

frontend/package.json
frontend/yarn.lock

with new version everting on negotiation page become download pdf and other bugs

fix: revert package because of bug

---

frontend/src/components/NegotiationList.vue

add a hand cursor when you hover over the entry

feat: add a hand cursor when you hover over the entry

---

backend/src/main/resources/db/migration/V20.3__increase_org_res_ntw_uri_column_size.sql
backend/src/test/java/eu/bbmri_eric/negotiator/integration/repository/NetworkRepositoryTest.java
backend/src/test/java/eu/bbmri_eric/negotiator/integration/repository/OrganizationRepositoryTest.java
backend/src/test/java/eu/bbmri_eric/negotiator/integration/repository/ResourceRepositoryTest.java

This PR implements #665 and increases URI column size for Organization, Resource and Network tables. 
- [ x] I have performed a self-review of my code
- [ x] I have made my code as simple as possible
- [ x] I have added relevant tests for my changes and the code coverage has not dropped substantially
- [ x] I have described the PR and added a meaningful title in the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) format

task:  Increase URI column size for Organizations, Resources and Networks

---

frontend/package.json
frontend/src/components/NegotiationPosts.vue
frontend/src/main.js
frontend/yarn.lock

Take a string as parameter, remove anything in there that can cause XSS, return that sanitized string for safe usage.
Custom setting has been added to remove all HTML tags

feat: sanitize html from xss

---

docs/.vitepress/config.mts
docs/SECURITY.md
docs/auth.md

- Fixes favicon on the documentation page
- Updates Security policy guidelines
- Add documentation on user roles

docs: update security policy and documentation

---

backend/src/main/java/eu/bbmri_eric/negotiator/negotiation/NegotiationServiceImpl.java
backend/src/main/java/eu/bbmri_eric/negotiator/negotiation/NegotiationSpecification.java
backend/src/main/java/eu/bbmri_eric/negotiator/negotiation/dto/NegotiationFilterDTO.java
backend/src/test/java/eu/bbmri_eric/negotiator/integration/api/v3/NetworkControllerTests.java
frontend/src/components/FilterSort.vue
frontend/src/store/networksPage.js
frontend/src/views/NetworksPage.vue
frontend/src/views/UserPage.vue

This PR adds a filter based on Organizations involved in Negotiations.

feat: add filtering for Organizations

---

frontend/package.json
frontend/yarn.lock

chore: upgrade vite from 6.0.11 to 6.1.1

---

docs/README.md
docs/REST.md

docs: fixes links

---

backend/src/main/java/eu/bbmri_eric/negotiator/governance/network/stats/NetworkStatsRepositoryImpl.java
backend/src/main/java/eu/bbmri_eric/negotiator/negotiation/NegotiationServiceImpl.java
backend/src/test/java/eu/bbmri_eric/negotiator/unit/service/NegotiationServiceTest.java

Fixes email being sent out for draft negotiations.

fix: email and notification creation for draft Negotiations

---

backend/pom.xml
backend/src/main/java/eu/bbmri_eric/negotiator/common/configuration/BaseConfig.java
backend/src/main/java/eu/bbmri_eric/negotiator/negotiation/NegotiationServiceImpl.java
backend/src/main/java/eu/bbmri_eric/negotiator/notification/UserNotificationService.java
backend/src/main/java/eu/bbmri_eric/negotiator/notification/UserNotificationServiceImpl.java
backend/src/main/java/eu/bbmri_eric/negotiator/notification/admin/AdminNotificationListener.java
backend/src/main/java/eu/bbmri_eric/negotiator/notification/researcher/ResearcherNotificationListener.java
backend/src/test/java/eu/bbmri_eric/negotiator/integration/listener/AdminNotificationListenerTest.java
backend/src/test/java/eu/bbmri_eric/negotiator/integration/listener/ResearcherNotificationListenerTest.java
backend/src/test/java/eu/bbmri_eric/negotiator/integration/service/NegotiationLifecycleServiceImplTest.java
backend/src/test/java/eu/bbmri_eric/negotiator/integration/service/UserNotificationServiceTest.java

This PR fixes issues when notifications were incorrectly sent out for draft Negotiations.

fix: notifications for draft/submitted Negotiations

---

backend/src/test/java/eu/bbmri_eric/negotiator/integration/api/v2/QueryV2ControllerTests.java
backend/src/test/java/eu/bbmri_eric/negotiator/integration/service/UserNotificationServiceTest.java

fix: integration test

---

frontend/src/components/NegotiationAttachment.vue
frontend/src/components/NegotiationForm.vue
frontend/src/components/OrganizationHeader.vue
frontend/src/views/NegotiationPage.vue

fix: pdf title overflows

---

frontend/package.json
frontend/src/components/NegotiationCard.vue
frontend/src/components/NegotiationList.vue
frontend/vitest.config.js
frontend/yarn.lock

chore: clear vite scss warnings

---

frontend/src/views/NetworksPage.vue

feat: jump network graph to negotiations list

---

backend/src/main/java/eu/bbmri_eric/negotiator/common/AuditEntity.java
backend/src/main/java/eu/bbmri_eric/negotiator/negotiation/NegotiationController.java
backend/src/main/java/eu/bbmri_eric/negotiator/negotiation/NegotiationServiceImpl.java
backend/src/main/java/eu/bbmri_eric/negotiator/negotiation/dto/NegotiationUpdateDTO.java
backend/src/test/java/eu/bbmri_eric/negotiator/integration/api/v3/NegotiationControllerTests.java
docs/.vitepress/config.mts
docs/requester.md
frontend/src/components/NavigationBar.vue
frontend/src/components/NegotiationSidebar.vue
frontend/src/components/PDFButton.vue
frontend/src/components/TransferButton.vue
frontend/src/components/modals/TransferNegotiationModal.vue
frontend/src/store/negotiationForm.js
frontend/src/views/NegotiationPage.vue

This PR adds support for transferring a Negotiation to a different user. This is done by providing a subject ID of the user to whom the Negotiation should be transferred. Currently, an Admin can transfer any Negotiation and any author can transfer their Negotiations.

feat: add support for transferring a Negotiation

---

backend/src/main/java/eu/bbmri_eric/negotiator/common/configuration/security/oauth2/CustomJWTAuthConverter.java
backend/src/main/java/eu/bbmri_eric/negotiator/user/LastLoginListener.java
backend/src/main/java/eu/bbmri_eric/negotiator/user/Person.java
backend/src/main/java/eu/bbmri_eric/negotiator/user/UserController.java
backend/src/main/java/eu/bbmri_eric/negotiator/user/UserInfoModel.java
backend/src/main/java/eu/bbmri_eric/negotiator/user/UserResponseModel.java
backend/src/main/resources/db/migration/V25.0__add_last_login.sql
backend/src/test/java/eu/bbmri_eric/negotiator/integration/api/LastLoginListenerTest.java
backend/src/test/java/eu/bbmri_eric/negotiator/integration/api/v3/UserControllerTest.java
frontend/src/components/InformationRequirementCard.vue
frontend/src/components/InformationRequirementsSection.vue
frontend/src/components/UserListSection.vue
frontend/src/components/modals/InfoRequirementModal.vue
frontend/src/components/modals/WebhookModal.vue
frontend/src/store/admin.js
frontend/src/views/AdminSettingsPage.vue

This PR adds a table to the Admin console listing all registered users in the Negotiator. It also introduces some refactoring of the console sections and unifies the style of entity creation modals

feat: add a table listing all registered users

---

backend/src/main/java/eu/bbmri_eric/negotiator/info_submission/InformationSubmissionServiceImpl.java
backend/src/test/java/eu/bbmri_eric/negotiator/integration/api/v3/InformationRequirementControllerTest.java
frontend/src/components/ResourceItem.vue
frontend/src/views/NegotiationPage.vue

This PR fixes the following minor bugs:
- HTML text parsing on Negotiation Page
- csv summary element order
- no "submitted" text for submission

fix: information summary related bugs

---

frontend/src/components/NegotiationForm.vue

feat: add save draft button, because users love it

---

frontend/src/components/modals/FormSubmissionModal.vue

Bug: if attachment is required, validation shows error, when file is correctly  selected. Validation function don't recognize attachment as valid input

fix: add missing validation for file

---

.github/workflows/CI.yml
.github/workflows/sonarqube.yml
.gitignore
backend/Dockerfile
backend/pom.xml
backend/src/test/java/eu/bbmri_eric/negotiator/TestNegotiatorApplication.java
docs/contributing.md

Upgrades the project to use Java 21

chore: upgrade the project to Java 21

---

docs/contributing.md
docs/requester.md

Add a more detailed documentation about the release process.

docs: improve release process documentation

---

frontend/src/components/NegotiationForm.vue
frontend/src/store/negotiationForm.js
frontend/src/views/NegotiationPage.vue

fix: disable file upload on every update of form data

---

frontend/src/views/HomePage.vue

Removed archived front-end repository link on login page

feat: remove archived front-end repository link

---

.github/copilot-instructions.md
.github/instructions/java.instructions.md
.github/instructions/spring.instructions.md
.github/instructions/vue.instructions.md

Add MD files with instructions for copilot.

chore: add github copilot instructions files

---

docs/.vitepress/config.mts
docs/deployment.md
docs/internationalization.md
frontend/README.md
frontend/package.json
frontend/src/components/NavigationBar.vue
frontend/src/components/ResourcesList.vue
frontend/src/config/i18n.js
frontend/src/main.js
frontend/src/views/NegotiationPage.vue
frontend/start.sh
frontend/yarn.lock

It allows developers to easily add multiple languages and manage translations within their projects

feat: add support for UI internationalization

---

frontend/src/components/TemplateSection.vue
frontend/src/store/templates.js

Fixes UI responsiveness on template update by redirecting the user back to the settings page

fix: UI responsiveness on template update

---

frontend/Dockerfile

Update the frontend/Dockerfile to use FROM bitnamilegacy/nginx:1.24 to fix the broken CI/CD pipeline.

Update the frontend/Dockerfile to use FROM bitnamilegacy/nginx:1.24

---

frontend/src/router/index.js

As a researcher I have no business going into the governance page. However this error message seem weird at best. Currently there is a method in index for verifying if as a user I'm allowed to visit a certain page. This does not make sense as the error page should be thrown up automatically if the API returns 401/403.
- [] I have updated the documentation in all relevant places (Javadoc, Swagger, MDs...)

903 bug fix error page on unauthorized views

---

frontend/src/components/ResourcesList.vue
frontend/src/components/form-components/AccessFormOverview.vue
frontend/src/components/form-components/FormNavigation.vue
frontend/src/router/index.js
frontend/src/views/NegotiationCreatePage.vue

This pull request introduces several UI and UX improvements to the resource list and form navigation components, along with some minor text updates and route simplifications. The main focus is on enhancing visual feedback, interactivity, and clarity for users navigating resource lists and multi-step forms.
**UI/UX Improvements to Form Navigation:**
* Updated the form navigation avatar styling for better visual feedback, including increased size, improved color usage, hover effects, and active state highlighting. Also improved text and icon alignment for clarity.
* Changed navigation item labels and icons for consistency and clarity (e.g., "Request summary" → "Request Parameters", `bi-file-text` → `bi-info-circle`). [[1]](diffhunk://#diff-fe086b283990b9b967f40bd41926a259b1c23581c363f56770cc …

feat: make the new design of the form page available by default
